[package]
name = "millet-sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "millet_sim"
path = "src/lib.rs"

[[bin]]
name = "msim"
path = "src/main.rs"

[[bin]]
name = "mview"
path = "src/mview.rs"

[dependencies]
millet-core = { path = "../millet-core" }
ratatui = { version = "0.30", default-features = false, features = ["crossterm"] }

[dev-dependencies]
millet-asm = { path = "../millet-asm" }
