name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --workspace --all-targets
      - run: cargo test --workspace
      - run: cargo fmt --all -- --check
